image: docker:20

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

Build:
  stage: build
  tags:
    - docker
  script:
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:latest
      .
    - PHP_VERSION=$(docker run --rm $CI_REGISTRY_IMAGE:latest -v | grep -Eo '8\.[0-9]\.[0-9]?[0-9]' | head -n 1)
    - docker push $CI_REGISTRY_IMAGE:v$PHP_VERSION
